version: "3.2"
services:
  postgres:    
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpass
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - convert_network 

  rabbitmq_broker:
    image: "rabbitmq:3.9.13-management"
    container_name: rabbitmq_broker
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=ConverterUser
      - RABBITMQ_DEFAULT_PASS=ConverterPass
    networks:
      - convert_network
    depends_on:
      - postgres      

  mcs_converter:
    image: mcs_converter:latest
    container_name: mcs_converter
    restart: always
    privileged: true
    environment:
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=dbpass
      - DB_PORT=5432
      - SEPARATOR_SO=/
      - RABBIT_HOST=rabbitmq_broker
      - HOME_PATH=/mnt/nfs_clientshare
    command: sh run_commands.sh
    build: ./services
    working_dir: /backend/
    volumes:
      - ./services/:/backend/
      # - nfs_shared:/mnt/nfs_clientshare/  
    networks:
      - convert_network
    depends_on:
      - postgres
      - rabbitmq_broker
  
  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - convert_network
    depends_on:
      - postgres    
      - mcs_converter

# volumes:
#   nfs_shared:
#     driver: local
#     driver_opts:
#       type: "nfs"
#       o: "addr=10.128.0.5,rsize=65536,wsize=65536,timeo=14,tcp,rw,noatime"
#       device: ":/mnt/nfs_share/"

networks:
  convert_network:
    driver: bridge