version: "3.2"
services:
  rabbitmq_broker:
    image: "rabbitmq:3.9.13-management"
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=ConverterUser
      - RABBITMQ_DEFAULT_PASS=ConverterPass
    networks:
      - convert_network

  celery_worker:
    image: celery_worker:latest
    privileged: true
    environment:
      - C_FORCE_ROOT=true
      - HOME_PATH=/mnt/nfs_clientshare
      - SEPARATOR_SO=/
      - DB_HOST=34.86.0.243
      - DB_USER=postgres
      - DB_PASS=dbpass
      - DB_NAME=postgres
    build: .
    working_dir: /backend/
    volumes:
      - nfs_shared:/mnt/nfs_clientshare/
    command: celery -A worker.celery worker --pool=solo -l info
    container_name: celery_worker
    restart: always
    networks:
      - convert_network
    depends_on:
      - rabbitmq_broker

volumes:
  nfs_shared:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.128.0.5,rsize=65536,wsize=65536,timeo=14,tcp,rw,noatime"
      device: ":/mnt/nfs_share/"

networks:
  convert_network:
    driver: bridge
